import { notFound } from 'next/navigation';
import Image from 'next/image';
import { createServerSupabaseClient } from '@/lib/auth';
import InfluencerClientPage from './InfluencerClientPage';

interface PageProps {
  params: {
    'influencer-slug': string;
  };
}

// Server Component to fetch influencer data
export default async function InfluencerPage({ params }: PageProps) {
  const slug = params['influencer-slug'];
  const supabase = createServerSupabaseClient();
  
  // Fetch influencer data from Supabase
  const { data: influencer, error } = await supabase
    .from('influencers')
    .select('*')
    .eq('slug', slug)
    .single();
  
  // Handle 404 if influencer not found
  if (error || !influencer) {
    notFound();
  }
  
  return (
    <div className="container mx-auto px-4 py-8 max-w-4xl">
      <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
        {/* Influencer Image Section */}
        <div className="rounded-lg overflow-hidden relative aspect-square">
          {influencer.photo_url ? (
            <Image 
              src={influencer.photo_url} 
              alt={influencer.name}
              fill
              className="object-cover"
              priority
            />
          ) : (
            <div className="w-full h-full bg-muted flex items-center justify-center">
              <p className="text-muted-foreground">Image not available</p>
            </div>
          )}
        </div>
        
        {/* Influencer Info and Demo Call Section */}
        <div className="flex flex-col space-y-6">
          <div>
            <h1 className="text-3xl md:text-4xl font-bold tracking-tight">{influencer.name}</h1>
            <p className="text-muted-foreground mt-2 text-lg">{influencer.bio}</p>
          </div>
          
          {/* Client Component for Call Functionality */}
          <InfluencerClientPage 
            influencerId={influencer.id} 
            influencerName={influencer.name}
            voiceId={influencer.voice_id || ''}
          />
          
          <div className="mt-auto pt-4">
            <p className="text-sm text-muted-foreground">
              *This is an AI-simulated experience and not actually {influencer.name}. 
              <br />The responses are generated by artificial intelligence trained on public data.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
} 